# scrape_configs:
#   - job_name: prometheus
#     scrape_interval: 5s
#     static_configs:
#     - targets:
#       - prometheus:9090
#       - node-exporter:9100
#       - pushgateway:9091
#       - cadvisor:8080
#       - localhost:1880
#     relabel_configs:
#       - source_labels: [__address__]
#         target_label: __param_target
#       - source_labels: [__param_target]
#         target_label: instance
#       - target_label: __address__
#         replacement: 192.168.174.41:9100
#   - job_name: docker
#     scrape_interval: 5s
#     static_configs:
#     - targets:
#       - 192.168.174.41:1880

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
    - targets:
      - prometheus:9090
      - node-exporter:9100
      - pushgateway:9091
      - cadvisor:8080

  - job_name: docker
    scrape_interval: 5s
    static_configs:
    - targets:
      - localhost:1880




# # scrape_configs:
# #   - job_name: 'docker'
# #     static_configs:
# #       - targets: ['localhost:9100']
# #     relabel_configs:
# #       - source_labels: [__address__]
# #         target_label: __param_target
# #       - source_labels: [__param_target]
# #         target_label: instance
# #       - target_label: __address__
# #         replacement: 192.168.174.41:9100
# #   - job_name: 'my-container'
# #     scrape_interval: 5s
# #     static_configs:
# #       - targets:
# #         - 192.168.174.41:1880


# global:
#   scrape_interval:     5s
#   evaluation_interval: 5s

# scrape_configs:
#   - job_name: cadvisor
#     scrape_interval: 5s
#     static_configs:
#       - targets:
#         - cadvisor:8080
#   - job_name: 'node-red'
#     metrics_path: '/metrics'
#     static_configs:
#       - targets: ['localhost:1880']